import '../models/restaurant.dart';
import '../models/menu_item.dart';

class MockData {
  static List<Restaurant> restaurants = [
    Restaurant(
      name: "Flavour Town",
      address: "12 Sunset Blvd, Springfield",
      menu: [
        MenuItem(name: "Cheese Burst Pizza", price: 250),
        MenuItem(name: "Spicy Veg Wrap", price: 150),
        MenuItem(name: "Classic Burger", price: 200),
        MenuItem(name: "Paneer Tikka Roll", price: 180),
        MenuItem(name: "Veggie Pasta", price: 220),
        MenuItem(name: "Grilled Sandwich", price: 140),
        MenuItem(name: "Crispy Fries", price: 100),
        MenuItem(name: "Cold Coffee", price: 120),
        MenuItem(name: "Chocolate Muffin", price: 90),
        MenuItem(name: "Lemonade", price: 80),
      ],
    ),
    Restaurant(
      name: "Tasty Treats",
      address: "45 Ocean Drive, Bayside",
      menu: [
        MenuItem(name: "BBQ Paneer Pizza", price: 280),
        MenuItem(name: "Veg Supreme Burger", price: 210),
        MenuItem(name: "Choco Shake", price: 150),
        MenuItem(name: "Masala Dosa", price: 120),
        MenuItem(name: "Aloo Paratha", price: 90),
        MenuItem(name: "Paneer Butter Masala", price: 200),
        MenuItem(name: "Veg Biryani", price: 180),
        MenuItem(name: "Coke Float", price: 110),
        MenuItem(name: "Fruit Salad", price: 130),
        MenuItem(name: "Garlic Bread", price: 100),
      ],
    ),
    Restaurant(
      name: "Spice Hub",
      address: "89 Market Street, Hillview",
      menu: [
        MenuItem(name: "Paneer Tikka Masala", price: 230),
        MenuItem(name: "Veg Hakka Noodles", price: 170),
        MenuItem(name: "Spring Rolls", price: 120),
        MenuItem(name: "Veg Fried Rice", price: 160),
        MenuItem(name: "Chili Paneer", price: 210),
        MenuItem(name: "Mango Lassi", price: 100),
        MenuItem(name: "Veg Momos", price: 130),
        MenuItem(name: "Masala Chai", price: 60),
        MenuItem(name: "Paneer Sandwich", price: 140),
        MenuItem(name: "Chocolate Brownie", price: 90),
      ],
    ),
    Restaurant(
      name: "Bite & Bliss",
      address: "23 River Road, Laketown",
      menu: [
        MenuItem(name: "Veggie Supreme Pizza", price: 260),
        MenuItem(name: "Paneer Wrap", price: 190),
        MenuItem(name: "Cheese Garlic Bread", price: 120),
        MenuItem(name: "Veg Burger", price: 170),
        MenuItem(name: "Cold Coffee", price: 110),
        MenuItem(name: "Mushroom Soup", price: 140),
        MenuItem(name: "Choco Chip Cookies", price: 80),
        MenuItem(name: "Fruit Yogurt", price: 100),
        MenuItem(name: "Veg Manchurian", price: 200),
        MenuItem(name: "Spring Roll Platter", price: 150),
      ],
    ),
    Restaurant(
      name: "Urban Feast",
      address: "77 Central Ave, Midtown",
      menu: [
        MenuItem(name: "Cheese Pizza", price: 220),
        MenuItem(name: "Veg Kathi Roll", price: 160),
        MenuItem(name: "Paneer Shawarma", price: 210),
        MenuItem(name: "Veg Biryani", price: 190),
        MenuItem(name: "Falafel Wrap", price: 180),
        MenuItem(name: "Mango Smoothie", price: 120),
        MenuItem(name: "Masala Fries", price: 110),
        MenuItem(name: "Veg Pasta Alfredo", price: 200),
        MenuItem(name: "Chocolate Shake", price: 140),
        MenuItem(name: "Lemon Iced Tea", price: 90),
      ],
    ),
    Restaurant(
      name: "Snack Shack",
      address: "15 Lakeview Road, Greenfield",
      menu: [
        MenuItem(name: "Cheese Nachos", price: 150),
        MenuItem(name: "Paneer Pakora", price: 120),
        MenuItem(name: "Veg Sandwich", price: 130),
        MenuItem(name: "French Fries", price: 90),
        MenuItem(name: "Veg Spring Rolls", price: 140),
        MenuItem(name: "Cold Coffee", price: 100),
        MenuItem(name: "Chocolate Muffin", price: 80),
        MenuItem(name: "Veg Wrap", price: 160),
        MenuItem(name: "Veg Burger", price: 150),
        MenuItem(name: "Fruit Salad", price: 110),
      ],
    ),
    Restaurant(
      name: "Grill & Go",
      address: "58 Hill Street, Brookside",
      menu: [
        MenuItem(name: "Grilled Paneer Sandwich", price: 200),
        MenuItem(name: "BBQ Veg Pizza", price: 270),
        MenuItem(name: "Paneer Tikka Burger", price: 220),
        MenuItem(name: "Veg Wrap", price: 170),
        MenuItem(name: "Veg Manchurian", price: 210),
        MenuItem(name: "Cheese Corn Balls", price: 150),
        MenuItem(name: "Cold Coffee", price: 110),
        MenuItem(name: "Veg Biryani", price: 190),
        MenuItem(name: "Masala Fries", price: 120),
        MenuItem(name: "Lemonade", price: 90),
      ],
    ),
    Restaurant(
      name: "The Food Factory",
      address: "34 Park Lane, Rivertown",
      menu: [
        MenuItem(name: "Veg Supreme Pizza", price: 280),
        MenuItem(name: "Paneer Tikka Roll", price: 200),
        MenuItem(name: "Cheese Burger", price: 170),
        MenuItem(name: "Veg Pasta", price: 210),
        MenuItem(name: "Cold Coffee", price: 120),
        MenuItem(name: "Veg Biryani", price: 190),
        MenuItem(name: "Chocolate Shake", price: 150),
        MenuItem(name: "Garlic Bread", price: 110),
        MenuItem(name: "Veg Sandwich", price: 140),
        MenuItem(name: "Spring Roll Platter", price: 160),
      ],
    ),
    Restaurant(
      name: "Munchies",
      address: "92 Broadway St, Sunnyside",
      menu: [
        MenuItem(name: "Cheese Pizza", price: 240),
        MenuItem(name: "Veg Kathi Roll", price: 170),
        MenuItem(name: "Paneer Shawarma", price: 220),
        MenuItem(name: "Veg Biryani", price: 200),
        MenuItem(name: "Falafel Wrap", price: 180),
        MenuItem(name: "Mango Smoothie", price: 120),
        MenuItem(name: "Masala Fries", price: 100),
        MenuItem(name: "Veg Pasta Alfredo", price: 210),
        MenuItem(name: "Chocolate Shake", price: 140),
        MenuItem(name: "Lemon Iced Tea", price: 90),
      ],
    ),
    Restaurant(
      name: "Chomp & Chill",
      address: "66 Elm Street, Riverview",
      menu: [
        MenuItem(name: "Veggie Supreme Pizza", price: 260),
        MenuItem(name: "Paneer Wrap", price: 180),
        MenuItem(name: "Cheese Garlic Bread", price: 120),
        MenuItem(name: "Veg Burger", price: 170),
        MenuItem(name: "Cold Coffee", price: 110),
        MenuItem(name: "Mushroom Soup", price: 140),
        MenuItem(name: "Choco Chip Cookies", price: 80),
        MenuItem(name: "Fruit Yogurt", price: 100),
        MenuItem(name: "Veg Manchurian", price: 200),
        MenuItem(name: "Spring Roll Platter", price: 150),
      ],
    ),
  ];
}
